begin;

create extension if not exists pgcrypto;

create or replace function public.zo2y_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (char_length(event_name) between 2 and 80),
  event_properties jsonb not null default '{}'::jsonb,
  page_url text null,
  referrer text null,
  user_agent text null,
  session_id text null,
  client_id text null,
  user_id uuid null references auth.users(id) on delete set null,
  ip_hash text null,
  source text not null default 'web',
  created_at timestamptz not null default now()
);

create index if not exists idx_analytics_events_created_at
  on public.analytics_events (created_at desc);

create index if not exists idx_analytics_events_event_name
  on public.analytics_events (event_name);

create index if not exists idx_analytics_events_user
  on public.analytics_events (user_id, created_at desc);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  name text null,
  email text null,
  category text not null default 'other'
    check (category in ('bug', 'billing', 'account', 'feature', 'abuse', 'other')),
  message text not null check (char_length(message) between 12 and 4000),
  status text not null default 'open'
    check (status in ('open', 'triaged', 'in_progress', 'resolved', 'closed', 'spam')),
  priority text not null default 'low'
    check (priority in ('low', 'medium', 'high')),
  page_url text null,
  user_agent text null,
  ip_hash text null,
  source text not null default 'web',
  user_id uuid null references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  admin_note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_support_tickets_status_created
  on public.support_tickets (status, created_at desc);

create index if not exists idx_support_tickets_user
  on public.support_tickets (user_id, created_at desc);

drop trigger if exists support_tickets_set_updated_at on public.support_tickets;
create trigger support_tickets_set_updated_at
before update on public.support_tickets
for each row execute function public.zo2y_set_updated_at();

alter table public.analytics_events enable row level security;
alter table public.support_tickets enable row level security;

drop policy if exists analytics_events_select_own on public.analytics_events;
create policy analytics_events_select_own
on public.analytics_events
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists support_tickets_select_own on public.support_tickets;
create policy support_tickets_select_own
on public.support_tickets
for select
to authenticated
using (user_id = auth.uid());

grant select on public.analytics_events to authenticated;
grant select on public.support_tickets to authenticated;

insert into public.analytics_events (event_name, event_properties, source)
values ('migration_bootstrap', jsonb_build_object('migration', 'production_readiness_core'), 'system')
on conflict do nothing;

commit;

