-- Generated 12/2/2025, 6:41:37 PM
-- Copy and run this in Supabase SQL Editor

UPDATE restraunts 
SET logo_url = CASE 
    WHEN slug = '88' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/88.jpg'
    WHEN slug = 'akleh' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/akleh.jpg'
    WHEN slug = 'barbar' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/barbar.png'
    WHEN slug = 'bayoki' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/bayoki.png'
    WHEN slug = 'bazooka' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/bazooka.jpg'
    WHEN slug = 'brgr' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/brgr.jpg'
    WHEN slug = 'buffalo' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/buffalo.jpg'
    WHEN slug = 'butchers' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/butchers.jpg'
    WHEN slug = 'caizo' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/caizo.jpg'
    WHEN slug = 'chez' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/chez.jpg'
    WHEN slug = 'chikin' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/chikin.png'
    WHEN slug = 'country' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/country.jpg'
    WHEN slug = 'crave' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/crave.png'
    WHEN slug = 'crispy' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/crispy.jpg'
    WHEN slug = 'crumbs' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/crumbs.jpg'
    WHEN slug = 'daddy' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/daddy.png'
    WHEN slug = 'dawgs' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/dawgs.jpg'
    WHEN slug = 'hameed' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/hameed.png'
    WHEN slug = 'hashville' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/hashville.png'
    WHEN slug = 'heart' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/heart.jpg'
    WHEN slug = 'holmes' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/holmes.jpg'
    WHEN slug = 'howlin' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/howlin.png'
    WHEN slug = 'husk' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/husk.jpg'
    WHEN slug = 'kansas' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/kansas.png'
    WHEN slug = 'kilo' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/kilo.png'
    WHEN slug = 'labash' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/labash.jpg'
    WHEN slug = 'lord' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/lord.png'
    WHEN slug = 'maine' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/maine.jpg'
    WHEN slug = 'man' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/man.png'
    WHEN slug = 'mario' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/mario.jpg'
    WHEN slug = 'mexican' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/mexican.jpg'
    WHEN slug = 'mince' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/mince.jpg'
    WHEN slug = 'mori' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/mori.png'
    WHEN slug = 'pablo' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/pablo.png'
    WHEN slug = 'panda' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/panda.png'
    WHEN slug = 'papa' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/papa.png'
    WHEN slug = 'pasta' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/pasta2go.png'
    WHEN slug = 'peking' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/peking.png'
    WHEN slug = 'pickl' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/pickl.jpg'
    WHEN slug = 'qasr' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/qasr.png'
    WHEN slug = 'ribs' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/ribs.jpg'
    WHEN slug = 'sauce' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/sauce.jpg'
    WHEN slug = 'secondcup' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/secondcup.png'
    WHEN slug = 'station' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/station.png'
    WHEN slug = 'tabali' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/tabali.jpg'
    WHEN slug = 'vasko' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/vasko.jpg'
    WHEN slug = 'ward' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/ward.png'
    WHEN slug = 'what' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/what.png'
    WHEN slug = 'willys' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/willys.png'
    WHEN slug = 'wok' THEN 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/restaurant-logos/wok.png'
    ELSE logo_url 
END;

-- Verify the update
SELECT id, slug, name, logo_url FROM restraunts ORDER BY id;