-- Activity feed table + triggers for profile community activity stream.
-- Run this once in Supabase SQL editor.

create table if not exists public.user_activity_feed (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('list_add', 'list_remove', 'review_add', 'review_edit', 'review_delete')),
  media_type text not null,
  item_id text,
  list_type text,
  list_id uuid,
  rating numeric(3,1),
  review_text text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_user_activity_feed_actor_created
  on public.user_activity_feed (actor_id, created_at desc);

create index if not exists idx_user_activity_feed_created
  on public.user_activity_feed (created_at desc);

alter table public.user_activity_feed enable row level security;

-- Ensure constraint supports update/delete activity if table already existed.
alter table public.user_activity_feed
  drop constraint if exists user_activity_feed_event_type_check;
alter table public.user_activity_feed
  add constraint user_activity_feed_event_type_check
  check (event_type in ('list_add', 'list_remove', 'review_add', 'review_edit', 'review_delete'));

drop policy if exists "activity_feed_select_public" on public.user_activity_feed;
create policy "activity_feed_select_public"
  on public.user_activity_feed
  for select
  to anon, authenticated
  using (true);

drop policy if exists "activity_feed_insert_own" on public.user_activity_feed;
create policy "activity_feed_insert_own"
  on public.user_activity_feed
  for insert
  to authenticated
  with check (auth.uid() = actor_id);

create or replace function public.log_list_activity_iud()
returns trigger
language plpgsql
as $$
declare
  v_event_type text;
  v_media_type text;
  v_item_id text;
  v_actor_id uuid;
  v_list_type text;
  v_list_id uuid;
  v_payload jsonb;
begin
  v_event_type := case tg_op
    when 'INSERT' then 'list_add'
    when 'DELETE' then 'list_remove'
    else null
  end;
  if v_event_type is null then
    return coalesce(new, old);
  end if;

  v_media_type := case tg_table_name
    when 'movie_list_items' then 'movie'
    when 'tv_list_items' then 'tv'
    when 'game_list_items' then 'game'
    when 'book_list_items' then 'book'
    when 'music_list_items' then 'music'
    else null
  end;

  v_payload := case
    when tg_op = 'INSERT' then to_jsonb(new)
    when tg_op = 'DELETE' then to_jsonb(old)
    else '{}'::jsonb
  end;

  v_item_id := case tg_table_name
    when 'movie_list_items' then nullif(v_payload->>'movie_id', '')
    when 'tv_list_items' then nullif(v_payload->>'tv_id', '')
    when 'game_list_items' then nullif(v_payload->>'game_id', '')
    when 'book_list_items' then nullif(v_payload->>'book_id', '')
    when 'music_list_items' then nullif(v_payload->>'track_id', '')
    else null
  end;
  v_actor_id := nullif(v_payload->>'user_id', '')::uuid;
  v_list_type := nullif(v_payload->>'list_type', '');
  v_list_id := nullif(v_payload->>'list_id', '')::uuid;

  if v_media_type is null or v_item_id is null or v_actor_id is null then
    return coalesce(new, old);
  end if;

  insert into public.user_activity_feed (
    actor_id,
    event_type,
    media_type,
    item_id,
    list_type,
    list_id,
    metadata
  ) values (
    v_actor_id,
    v_event_type,
    v_media_type,
    v_item_id,
    v_list_type,
    v_list_id,
    jsonb_build_object('source_table', tg_table_name)
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_movie_list_add_activity on public.movie_list_items;
create trigger trg_movie_list_add_activity
after insert on public.movie_list_items
for each row
execute function public.log_list_activity_iud();

drop trigger if exists trg_movie_list_remove_activity on public.movie_list_items;
create trigger trg_movie_list_remove_activity
after delete on public.movie_list_items
for each row
execute function public.log_list_activity_iud();

drop trigger if exists trg_tv_list_add_activity on public.tv_list_items;
create trigger trg_tv_list_add_activity
after insert on public.tv_list_items
for each row
execute function public.log_list_activity_iud();

drop trigger if exists trg_tv_list_remove_activity on public.tv_list_items;
create trigger trg_tv_list_remove_activity
after delete on public.tv_list_items
for each row
execute function public.log_list_activity_iud();

drop trigger if exists trg_game_list_add_activity on public.game_list_items;
create trigger trg_game_list_add_activity
after insert on public.game_list_items
for each row
execute function public.log_list_activity_iud();

drop trigger if exists trg_game_list_remove_activity on public.game_list_items;
create trigger trg_game_list_remove_activity
after delete on public.game_list_items
for each row
execute function public.log_list_activity_iud();

drop trigger if exists trg_book_list_add_activity on public.book_list_items;
create trigger trg_book_list_add_activity
after insert on public.book_list_items
for each row
execute function public.log_list_activity_iud();

drop trigger if exists trg_book_list_remove_activity on public.book_list_items;
create trigger trg_book_list_remove_activity
after delete on public.book_list_items
for each row
execute function public.log_list_activity_iud();

drop trigger if exists trg_music_list_add_activity on public.music_list_items;
create trigger trg_music_list_add_activity
after insert on public.music_list_items
for each row
execute function public.log_list_activity_iud();

drop trigger if exists trg_music_list_remove_activity on public.music_list_items;
create trigger trg_music_list_remove_activity
after delete on public.music_list_items
for each row
execute function public.log_list_activity_iud();

create or replace function public.log_journal_review_activity_iud()
returns trigger
language plpgsql
as $$
declare
  v_event_type text;
  v_row journal_entries%rowtype;
begin
  if tg_op = 'INSERT' then
    v_event_type := 'review_add';
    v_row := new;
  elsif tg_op = 'UPDATE' then
    v_event_type := 'review_edit';
    v_row := new;
  elsif tg_op = 'DELETE' then
    v_event_type := 'review_delete';
    v_row := old;
  else
    return coalesce(new, old);
  end if;

  insert into public.user_activity_feed (
    actor_id,
    event_type,
    media_type,
    item_id,
    rating,
    review_text,
    metadata
  ) values (
    v_row.user_id,
    v_event_type,
    'restaurant',
    v_row.restraunt_id::text,
    v_row.rating,
    nullif(trim(v_row.notes), ''),
    jsonb_build_object(
      'visit_date', v_row.visit_date,
      'tags', v_row.tags
    )
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_journal_review_add_activity on public.journal_entries;
create trigger trg_journal_review_add_activity
after insert on public.journal_entries
for each row
execute function public.log_journal_review_activity_iud();

drop trigger if exists trg_journal_review_edit_activity on public.journal_entries;
create trigger trg_journal_review_edit_activity
after update of rating, notes, visit_date, tags on public.journal_entries
for each row
execute function public.log_journal_review_activity_iud();

drop trigger if exists trg_journal_review_delete_activity on public.journal_entries;
create trigger trg_journal_review_delete_activity
after delete on public.journal_entries
for each row
execute function public.log_journal_review_activity_iud();

-- Ensure Supabase REST picks up new table/functions promptly.
notify pgrst, 'reload schema';
