-- Activity feed table + triggers for profile community activity stream.
-- Run this in Supabase SQL editor whenever schema or activity mappings change.

create table if not exists public.user_activity_feed (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (
    event_type in (
      'list_create',
      'list_delete',
      'list_add',
      'list_remove',
      'review_add',
      'review_edit',
      'review_delete'
    )
  ),
  media_type text not null,
  item_id text,
  list_type text,
  list_id uuid,
  rating numeric(3,1),
  review_text text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_user_activity_feed_actor_created
  on public.user_activity_feed (actor_id, created_at desc);

create index if not exists idx_user_activity_feed_created
  on public.user_activity_feed (created_at desc);

alter table public.user_activity_feed enable row level security;

-- Keep the check constraint current if table already exists.
alter table public.user_activity_feed
  drop constraint if exists user_activity_feed_event_type_check;
alter table public.user_activity_feed
  add constraint user_activity_feed_event_type_check
  check (
    event_type in (
      'list_create',
      'list_delete',
      'list_add',
      'list_remove',
      'review_add',
      'review_edit',
      'review_delete'
    )
  );

-- ============================================================================
-- UNIFIED LIST ACTIVITY FUNCTIONS
-- These are also defined in rebuild_all.sql; running this file updates them.
-- ============================================================================

create or replace function public.log_list_activity_iud()
returns trigger language plpgsql as $$
declare
  v_event_type text; v_media_type text; v_item_id text; v_actor_id uuid;
  v_list_type text; v_list_id uuid; v_payload jsonb; v_list public.user_lists;
begin
  v_event_type := case tg_op when 'INSERT' then 'list_add' when 'DELETE' then 'list_remove' else null end;
  if v_event_type is null then return coalesce(new, old); end if;
  v_payload := case when tg_op = 'INSERT' then to_jsonb(new) when tg_op = 'DELETE' then to_jsonb(old) else '{}'::jsonb end;

  if tg_table_name = 'list_items' then
    v_item_id := nullif(v_payload->>'external_id', '');
    v_list_id := nullif(v_payload->>'list_id', '')::uuid;
    if v_list_id is not null then
      select * into v_list from public.user_lists where id = v_list_id;
      v_media_type := v_list.category::text;
      v_list_type := v_list.type::text;
      v_actor_id := v_list.user_id;
    end if;
  end if;

  if v_media_type is null or v_item_id is null or v_actor_id is null then return coalesce(new, old); end if;
  insert into public.user_activity_feed (actor_id, event_type, media_type, item_id, list_type, list_id, metadata)
  values (v_actor_id, v_event_type, v_media_type, v_item_id, v_list_type, v_list_id,
    jsonb_build_object('source_table', tg_table_name, 'source_pk', nullif(v_payload->>'id', '')));
  return coalesce(new, old);
end;
$$;

create or replace function public.log_custom_list_activity_iud()
returns trigger language plpgsql as $$
declare
  v_event_type text; v_media_type text; v_actor_id uuid;
  v_list_id uuid; v_list_title text; v_payload jsonb;
begin
  v_event_type := case tg_op when 'INSERT' then 'list_create' when 'DELETE' then 'list_delete' else null end;
  if v_event_type is null then return coalesce(new, old); end if;
  v_payload := case when tg_op = 'INSERT' then to_jsonb(new) when tg_op = 'DELETE' then to_jsonb(old) else '{}'::jsonb end;

  if tg_table_name = 'user_lists' then
    v_actor_id := nullif(v_payload->>'user_id', '')::uuid;
    v_list_id := nullif(v_payload->>'id', '')::uuid;
    v_list_title := nullif(trim(v_payload->>'name'), '');
    v_media_type := nullif(v_payload->>'category', '');
  end if;

  if v_media_type is null or v_actor_id is null or v_list_id is null then return coalesce(new, old); end if;
  insert into public.user_activity_feed (actor_id, event_type, media_type, list_id, metadata)
  values (v_actor_id, v_event_type, v_media_type, v_list_id,
    jsonb_build_object('source_table', tg_table_name, 'source_pk', nullif(v_payload->>'id', ''), 'list_title', v_list_title));
  return coalesce(new, old);
end;
$$;

create or replace function public.log_media_review_activity_iud()
returns trigger language plpgsql as $$
declare
  v_event_type text; v_media_type text; v_actor_id uuid; v_item_id text;
  v_review_text text; v_rating numeric(3,1); v_payload jsonb; v_metadata jsonb;
begin
  v_event_type := case tg_op when 'INSERT' then 'review_add' when 'UPDATE' then 'review_edit' when 'DELETE' then 'review_delete' else null end;
  if v_event_type is null then return coalesce(new, old); end if;
  v_media_type := case tg_table_name
    when 'movie_reviews' then 'movie' when 'tv_reviews' then 'tv'
    when 'anime_reviews' then 'anime' when 'game_reviews' then 'game'
    when 'book_reviews' then 'book' when 'music_reviews' then 'music'
    when 'user_album_reviews' then 'music'
    else null end;
  v_payload := case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) when tg_op = 'DELETE' then to_jsonb(old) else '{}'::jsonb end;
  v_actor_id := nullif(v_payload->>'user_id', '')::uuid;
  v_item_id := nullif(v_payload->>'media_id', '');
  v_review_text := nullif(trim(coalesce(v_payload->>'review_text', v_payload->>'comment', '')), '');
  v_rating := nullif(v_payload->>'rating', '')::numeric(3,1);
  v_metadata := jsonb_build_object('source_table', tg_table_name, 'source_pk', nullif(v_payload->>'id', ''));
  if v_media_type is null or v_actor_id is null or v_item_id is null then return coalesce(new, old); end if;
  insert into public.user_activity_feed (actor_id, event_type, media_type, item_id, rating, review_text, metadata)
  values (v_actor_id, v_event_type, v_media_type, v_item_id, v_rating, v_review_text, v_metadata);
  return coalesce(new, old);
end;
$$;

create or replace function public.ensure_activity_trigger(
  p_table_name text, p_trigger_name text, p_events text, p_function_name text
)
returns void language plpgsql as $$
declare
  v_relkind char;
begin
  if to_regclass(format('public.%s', p_table_name)) is null then return; end if;
  select relkind into v_relkind from pg_class where oid = format('public.%s', p_table_name)::regclass;
  if v_relkind IS DISTINCT FROM 'r' then return; end if;
  execute format('drop trigger if exists %I on public.%I', p_trigger_name, p_table_name);
  execute format('create trigger %I after %s on public.%I for each row execute function %s()',
    p_trigger_name, p_events, p_table_name, p_function_name);
end;
$$;

-- List items triggers (unified)
select ensure_activity_trigger('list_items', 'trg_list_items_add_activity', 'insert', 'public.log_list_activity_iud');
select ensure_activity_trigger('list_items', 'trg_list_items_remove_activity', 'delete', 'public.log_list_activity_iud');

-- Custom list triggers (unified)
select ensure_activity_trigger('user_lists', 'trg_user_lists_create_activity', 'insert', 'public.log_custom_list_activity_iud');
select ensure_activity_trigger('user_lists', 'trg_user_lists_delete_activity', 'delete', 'public.log_custom_list_activity_iud');

-- Review triggers
select ensure_activity_trigger('movie_reviews', 'trg_movie_review_add_activity', 'insert', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('movie_reviews', 'trg_movie_review_edit_activity', 'update of rating, comment', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('movie_reviews', 'trg_movie_review_delete_activity', 'delete', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('tv_reviews', 'trg_tv_review_add_activity', 'insert', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('tv_reviews', 'trg_tv_review_edit_activity', 'update of rating, comment', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('tv_reviews', 'trg_tv_review_delete_activity', 'delete', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('anime_reviews', 'trg_anime_review_add_activity', 'insert', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('anime_reviews', 'trg_anime_review_edit_activity', 'update of rating, comment', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('anime_reviews', 'trg_anime_review_delete_activity', 'delete', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('game_reviews', 'trg_game_review_add_activity', 'insert', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('game_reviews', 'trg_game_review_edit_activity', 'update of rating, comment', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('game_reviews', 'trg_game_review_delete_activity', 'delete', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('book_reviews', 'trg_book_review_add_activity', 'insert', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('book_reviews', 'trg_book_review_edit_activity', 'update of rating, comment', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('book_reviews', 'trg_book_review_delete_activity', 'delete', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('music_reviews', 'trg_music_review_add_activity', 'insert', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('music_reviews', 'trg_music_review_edit_activity', 'update of rating, comment', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('music_reviews', 'trg_music_review_delete_activity', 'delete', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('user_album_reviews', 'trg_album_review_add_activity', 'insert', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('user_album_reviews', 'trg_album_review_edit_activity', 'update of rating, comment', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('user_album_reviews', 'trg_album_review_delete_activity', 'delete', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('fashion_reviews', 'trg_fashion_review_add_activity', 'insert', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('fashion_reviews', 'trg_fashion_review_edit_activity', 'update of rating, review_text', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('fashion_reviews', 'trg_fashion_review_delete_activity', 'delete', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('food_reviews', 'trg_food_review_add_activity', 'insert', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('food_reviews', 'trg_food_review_edit_activity', 'update of rating, review_text', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('food_reviews', 'trg_food_review_delete_activity', 'delete', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('car_reviews', 'trg_car_review_add_activity', 'insert', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('car_reviews', 'trg_car_review_edit_activity', 'update of rating, review_text', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('car_reviews', 'trg_car_review_delete_activity', 'delete', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('travel_reviews', 'trg_travel_review_add_activity', 'insert', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('travel_reviews', 'trg_travel_review_edit_activity', 'update of rating, comment', 'public.log_media_review_activity_iud');
select ensure_activity_trigger('travel_reviews', 'trg_travel_review_delete_activity', 'delete', 'public.log_media_review_activity_iud');

drop function if exists public.ensure_activity_trigger(text, text, text, text);

-- Best-effort backfill for existing rows so feed is populated immediately.
do $$
declare
  rt text[]; rtype text; rtab text; rcol text;
  revs text[][] := ARRAY[
    ARRAY['movie_reviews','movie'], ARRAY['tv_reviews','tv'],
    ARRAY['anime_reviews','anime'], ARRAY['game_reviews','game'],
    ARRAY['book_reviews','book'], ARRAY['music_reviews','music'],
    ARRAY['user_album_reviews','music']
  ];
begin
  -- Backfill list item activity from unified tables
  if to_regclass('public.list_items') is not null then
    insert into public.user_activity_feed (actor_id, event_type, media_type, item_id, list_type, list_id, metadata, created_at)
    select ul.user_id, 'list_add', ul.category::text, li.external_id, ul.type::text, li.list_id,
      jsonb_build_object('source_table', 'list_items', 'source_pk', li.id::text, 'backfill', true),
      coalesce(li.added_at, now())
    from public.list_items li
    join public.user_lists ul on ul.id = li.list_id
    where ul.user_id is not null and li.external_id is not null
      and not exists (select 1 from public.user_activity_feed f where f.event_type = 'list_add' and f.metadata->>'source_table' = 'list_items' and f.metadata->>'source_pk' = li.id::text);
  end if;

  -- Backfill custom list creation from unified tables
  if to_regclass('public.user_lists') is not null then
    insert into public.user_activity_feed (actor_id, event_type, media_type, list_id, metadata, created_at)
    select ul.user_id, 'list_create', ul.category::text, ul.id,
      jsonb_build_object('source_table', 'user_lists', 'source_pk', ul.id::text, 'list_title', ul.name, 'backfill', true),
      coalesce(ul.created_at, now())
    from public.user_lists ul
    where ul.user_id is not null
      and not exists (select 1 from public.user_activity_feed f where f.event_type = 'list_create' and f.metadata->>'source_table' = 'user_lists' and f.metadata->>'source_pk' = ul.id::text);
  end if;

  -- Backfill review activity — generic per-table using dynamic item_id column
  foreach rt slice 1 in array revs loop
    rtab := rt[1]; rtype := rt[2];
    if to_regclass(format('public.%s', rtab)) is null then continue; end if;
    rcol := coalesce(
      (select column_name from information_schema.columns where table_schema='public' and table_name=rtab and column_name='media_id' limit 1),
      (select column_name from information_schema.columns where table_schema='public' and table_name=rtab and column_name like '%_id' and column_name not in ('id','user_id') limit 1),
      'media_id'
    );
    execute format(
      'insert into public.user_activity_feed (actor_id, event_type, media_type, item_id, rating, review_text, metadata, created_at)
         select src.user_id, $1, $2, src.%I::text, src.rating::numeric(3,1), nullif(trim(src.review_text), $3),
         jsonb_build_object($4, $5, $6, src.id::text, $7, true),
         coalesce(src.created_at, now())
       from public.%I src
       where src.user_id is not null and src.%I is not null
         and not exists (select 1 from public.user_activity_feed f where f.event_type = $8 and f.media_type = $9 and f.metadata->>$10 = src.id::text)',
      rcol, rtab, rcol
    ) using 'review_add', rtype, '', 'source_table', rtab, 'source_pk', 'backfill', 'review_add', rtype, 'source_pk';
  end loop;
end
$$;

-- Ensure Supabase REST picks up new table/functions promptly.
notify pgrst, 'reload schema';
