-- Activity feed table + triggers for profile community activity stream.
-- Run this once in Supabase SQL editor.

create table if not exists public.user_activity_feed (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('list_add', 'review_add')),
  media_type text not null,
  item_id text,
  list_type text,
  list_id uuid,
  rating numeric(3,1),
  review_text text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_user_activity_feed_actor_created
  on public.user_activity_feed (actor_id, created_at desc);

create index if not exists idx_user_activity_feed_created
  on public.user_activity_feed (created_at desc);

alter table public.user_activity_feed enable row level security;

drop policy if exists "activity_feed_select_public" on public.user_activity_feed;
create policy "activity_feed_select_public"
  on public.user_activity_feed
  for select
  to anon, authenticated
  using (true);

drop policy if exists "activity_feed_insert_own" on public.user_activity_feed;
create policy "activity_feed_insert_own"
  on public.user_activity_feed
  for insert
  to authenticated
  with check (auth.uid() = actor_id);

create or replace function public.log_list_add_activity()
returns trigger
language plpgsql
as $$
declare
  v_media_type text;
  v_item_id text;
begin
  v_media_type := case tg_table_name
    when 'movie_list_items' then 'movie'
    when 'tv_list_items' then 'tv'
    when 'game_list_items' then 'game'
    when 'book_list_items' then 'book'
    when 'music_list_items' then 'music'
    else null
  end;

  v_item_id := case tg_table_name
    when 'movie_list_items' then new.movie_id::text
    when 'tv_list_items' then new.tv_id::text
    when 'game_list_items' then new.game_id::text
    when 'book_list_items' then new.book_id::text
    when 'music_list_items' then new.track_id::text
    else null
  end;

  if v_media_type is null or v_item_id is null then
    return new;
  end if;

  insert into public.user_activity_feed (
    actor_id,
    event_type,
    media_type,
    item_id,
    list_type,
    list_id,
    metadata
  ) values (
    new.user_id,
    'list_add',
    v_media_type,
    v_item_id,
    new.list_type,
    new.list_id,
    jsonb_build_object('source_table', tg_table_name)
  );

  return new;
end;
$$;

drop trigger if exists trg_movie_list_add_activity on public.movie_list_items;
create trigger trg_movie_list_add_activity
after insert on public.movie_list_items
for each row
execute function public.log_list_add_activity();

drop trigger if exists trg_tv_list_add_activity on public.tv_list_items;
create trigger trg_tv_list_add_activity
after insert on public.tv_list_items
for each row
execute function public.log_list_add_activity();

drop trigger if exists trg_game_list_add_activity on public.game_list_items;
create trigger trg_game_list_add_activity
after insert on public.game_list_items
for each row
execute function public.log_list_add_activity();

drop trigger if exists trg_book_list_add_activity on public.book_list_items;
create trigger trg_book_list_add_activity
after insert on public.book_list_items
for each row
execute function public.log_list_add_activity();

drop trigger if exists trg_music_list_add_activity on public.music_list_items;
create trigger trg_music_list_add_activity
after insert on public.music_list_items
for each row
execute function public.log_list_add_activity();

create or replace function public.log_journal_review_activity()
returns trigger
language plpgsql
as $$
begin
  insert into public.user_activity_feed (
    actor_id,
    event_type,
    media_type,
    item_id,
    rating,
    review_text,
    metadata
  ) values (
    new.user_id,
    'review_add',
    'restaurant',
    new.restraunt_id::text,
    new.rating,
    nullif(trim(new.notes), ''),
    jsonb_build_object(
      'visit_date', new.visit_date,
      'tags', new.tags
    )
  );

  return new;
end;
$$;

drop trigger if exists trg_journal_review_add_activity on public.journal_entries;
create trigger trg_journal_review_add_activity
after insert on public.journal_entries
for each row
execute function public.log_journal_review_activity();
