begin;

create extension if not exists pgcrypto;

create or replace function public.zo2y_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.list_collaborators (
  id bigint generated by default as identity primary key,
  media_type text not null check (media_type in ('restaurant', 'movie', 'tv', 'game', 'book', 'music')),
  list_id text not null,
  list_owner_id uuid not null references auth.users(id) on delete cascade,
  collaborator_id uuid not null references auth.users(id) on delete cascade,
  can_edit boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (media_type, list_id, collaborator_id),
  check (list_owner_id <> collaborator_id)
);

create index if not exists idx_list_collaborators_collab_lookup
  on public.list_collaborators (collaborator_id, media_type, list_id);

create index if not exists idx_list_collaborators_owner_lookup
  on public.list_collaborators (list_owner_id, media_type, list_id);

drop trigger if exists list_collaborators_set_updated_at on public.list_collaborators;
create trigger list_collaborators_set_updated_at
before update on public.list_collaborators
for each row execute function public.zo2y_set_updated_at();

create or replace function public.zo2y_has_mutual_follow(p_user_a uuid, p_user_b uuid)
returns boolean
language plpgsql
stable
as $$
declare
  has_relation boolean := false;
begin
  if p_user_a is null or p_user_b is null or p_user_a = p_user_b then
    return false;
  end if;

  if to_regclass('public.follows') is null then
    return false;
  end if;

  execute $q$
    select
      exists (
        select 1
        from public.follows f
        where f.follower_id = $1
          and f.followed_id = $2
      )
      and
      exists (
        select 1
        from public.follows f
        where f.follower_id = $2
          and f.followed_id = $1
      )
  $q$
  into has_relation
  using p_user_a, p_user_b;

  return coalesce(has_relation, false);
end;
$$;

alter table public.list_collaborators enable row level security;

drop policy if exists list_collaborators_select_owner_or_collaborator on public.list_collaborators;
create policy list_collaborators_select_owner_or_collaborator
on public.list_collaborators
for select
to authenticated
using (collaborator_id = auth.uid() or list_owner_id = auth.uid());

drop policy if exists list_collaborators_insert_owner on public.list_collaborators;
create policy list_collaborators_insert_owner
on public.list_collaborators
for insert
to authenticated
with check (
  list_owner_id = auth.uid()
  and public.zo2y_has_mutual_follow(list_owner_id, collaborator_id)
);

drop policy if exists list_collaborators_update_owner on public.list_collaborators;
create policy list_collaborators_update_owner
on public.list_collaborators
for update
to authenticated
using (list_owner_id = auth.uid())
with check (
  list_owner_id = auth.uid()
  and public.zo2y_has_mutual_follow(list_owner_id, collaborator_id)
);

drop policy if exists list_collaborators_delete_owner on public.list_collaborators;
create policy list_collaborators_delete_owner
on public.list_collaborators
for delete
to authenticated
using (list_owner_id = auth.uid());

grant select, insert, update, delete on public.list_collaborators to authenticated;
grant usage, select on sequence public.list_collaborators_id_seq to authenticated;

create or replace function public.cleanup_media_list_dependents()
returns trigger
language plpgsql
as $$
begin
  delete from public.list_collaborators
  where media_type = tg_argv[0]
    and list_id = old.id::text;

  if to_regclass('public.list_tier_meta') is not null then
    delete from public.list_tier_meta
    where media_type = tg_argv[0]
      and list_id = old.id::text
      and user_id = old.user_id;
  end if;

  if to_regclass('public.list_tier_ranks') is not null then
    delete from public.list_tier_ranks
    where media_type = tg_argv[0]
      and list_id = old.id::text
      and user_id = old.user_id;
  end if;

  return old;
end;
$$;

drop trigger if exists trg_movie_lists_cleanup_dependents on public.movie_lists;
create trigger trg_movie_lists_cleanup_dependents
after delete on public.movie_lists
for each row execute function public.cleanup_media_list_dependents('movie');

drop trigger if exists trg_tv_lists_cleanup_dependents on public.tv_lists;
create trigger trg_tv_lists_cleanup_dependents
after delete on public.tv_lists
for each row execute function public.cleanup_media_list_dependents('tv');

drop trigger if exists trg_game_lists_cleanup_dependents on public.game_lists;
create trigger trg_game_lists_cleanup_dependents
after delete on public.game_lists
for each row execute function public.cleanup_media_list_dependents('game');

drop trigger if exists trg_book_lists_cleanup_dependents on public.book_lists;
create trigger trg_book_lists_cleanup_dependents
after delete on public.book_lists
for each row execute function public.cleanup_media_list_dependents('book');

drop trigger if exists trg_music_lists_cleanup_dependents on public.music_lists;
create trigger trg_music_lists_cleanup_dependents
after delete on public.music_lists
for each row execute function public.cleanup_media_list_dependents('music');

do $$
declare
  rec record;
begin
  for rec in
    select *
    from (values
      ('movie', 'movie_lists', 'movie_list_items', 'movie_id'),
      ('tv', 'tv_lists', 'tv_list_items', 'tv_id'),
      ('game', 'game_lists', 'game_list_items', 'game_id'),
      ('book', 'book_lists', 'book_list_items', 'book_id'),
      ('music', 'music_lists', 'music_list_items', 'track_id')
    ) as t(media_type, list_table, item_table, item_field)
  loop
    if to_regclass(format('public.%s', rec.list_table)) is null
       or to_regclass(format('public.%s', rec.item_table)) is null then
      continue;
    end if;

    execute format('drop policy if exists %I on public.%I', rec.list_table || '_select_collaborator', rec.list_table);
    execute format(
      'create policy %I on public.%I for select to authenticated using (
        exists (
          select 1 from public.list_collaborators lc
          where lc.media_type = %L
            and lc.list_id = %I.id::text
            and lc.collaborator_id = auth.uid()
        )
      )',
      rec.list_table || '_select_collaborator',
      rec.list_table,
      rec.media_type,
      rec.list_table
    );

    execute format('drop policy if exists %I on public.%I', rec.list_table || '_update_collaborator', rec.list_table);
    execute format(
      'create policy %I on public.%I for update to authenticated
       using (
         exists (
           select 1 from public.list_collaborators lc
           where lc.media_type = %L
             and lc.list_id = %I.id::text
             and lc.collaborator_id = auth.uid()
             and lc.can_edit = true
             and lc.list_owner_id = %I.user_id
         )
       )
       with check (
         exists (
           select 1 from public.list_collaborators lc
           where lc.media_type = %L
             and lc.list_id = %I.id::text
             and lc.collaborator_id = auth.uid()
             and lc.can_edit = true
             and lc.list_owner_id = %I.user_id
         )
       )',
      rec.list_table || '_update_collaborator',
      rec.list_table,
      rec.media_type,
      rec.list_table,
      rec.list_table,
      rec.media_type,
      rec.list_table,
      rec.list_table
    );

    execute format(
      'with dedupe as (
         select id,
                row_number() over (partition by list_id, %I order by created_at asc nulls last, id asc) as rn
         from public.%I
         where list_id is not null
       )
       delete from public.%I i
       using dedupe d
       where i.id = d.id
         and d.rn > 1',
      rec.item_field,
      rec.item_table,
      rec.item_table
    );

    execute format(
      'create unique index if not exists %I
       on public.%I (list_id, %I)
       where list_id is not null',
      'ux_' || rec.item_table || '_custom_unique',
      rec.item_table,
      rec.item_field
    );

    execute format('drop policy if exists %I on public.%I', rec.item_table || '_select_collaborator', rec.item_table);
    execute format(
      'create policy %I on public.%I for select to authenticated
       using (
         list_id is not null
         and exists (
           select 1 from public.list_collaborators lc
           where lc.media_type = %L
             and lc.list_id = %I.list_id::text
             and lc.collaborator_id = auth.uid()
         )
       )',
      rec.item_table || '_select_collaborator',
      rec.item_table,
      rec.media_type,
      rec.item_table
    );

    execute format('drop policy if exists %I on public.%I', rec.item_table || '_insert_collaborator', rec.item_table);
    execute format(
      'create policy %I on public.%I for insert to authenticated
       with check (
         list_id is not null
         and exists (
           select 1 from public.list_collaborators lc
           where lc.media_type = %L
             and lc.list_id = %I.list_id::text
             and lc.collaborator_id = auth.uid()
             and lc.can_edit = true
         )
         and exists (
           select 1 from public.%I l
           where l.id = %I.list_id
             and l.user_id = %I.user_id
         )
       )',
      rec.item_table || '_insert_collaborator',
      rec.item_table,
      rec.media_type,
      rec.item_table,
      rec.list_table,
      rec.item_table,
      rec.item_table
    );

    execute format('drop policy if exists %I on public.%I', rec.item_table || '_update_collaborator', rec.item_table);
    execute format(
      'create policy %I on public.%I for update to authenticated
       using (
         list_id is not null
         and exists (
           select 1 from public.list_collaborators lc
           where lc.media_type = %L
             and lc.list_id = %I.list_id::text
             and lc.collaborator_id = auth.uid()
             and lc.can_edit = true
         )
       )
       with check (
         list_id is not null
         and exists (
           select 1 from public.list_collaborators lc
           where lc.media_type = %L
             and lc.list_id = %I.list_id::text
             and lc.collaborator_id = auth.uid()
             and lc.can_edit = true
         )
         and exists (
           select 1 from public.%I l
           where l.id = %I.list_id
             and l.user_id = %I.user_id
         )
       )',
      rec.item_table || '_update_collaborator',
      rec.item_table,
      rec.media_type,
      rec.item_table,
      rec.media_type,
      rec.item_table,
      rec.list_table,
      rec.item_table,
      rec.item_table
    );

    execute format('drop policy if exists %I on public.%I', rec.item_table || '_delete_collaborator', rec.item_table);
    execute format(
      'create policy %I on public.%I for delete to authenticated
       using (
         list_id is not null
         and exists (
           select 1 from public.list_collaborators lc
           where lc.media_type = %L
             and lc.list_id = %I.list_id::text
             and lc.collaborator_id = auth.uid()
             and lc.can_edit = true
         )
       )',
      rec.item_table || '_delete_collaborator',
      rec.item_table,
      rec.media_type,
      rec.item_table
    );

    execute format('drop policy if exists %I on public.%I', rec.item_table || '_update_owner_by_list', rec.item_table);
    execute format(
      'create policy %I on public.%I for update to authenticated
       using (
         list_id is not null
         and exists (
           select 1 from public.%I l
           where l.id = %I.list_id
             and l.user_id = auth.uid()
         )
       )
       with check (
         list_id is not null
         and exists (
           select 1 from public.%I l
           where l.id = %I.list_id
             and l.user_id = auth.uid()
             and l.user_id = %I.user_id
         )
       )',
      rec.item_table || '_update_owner_by_list',
      rec.item_table,
      rec.list_table,
      rec.item_table,
      rec.list_table,
      rec.item_table,
      rec.item_table
    );

    execute format('drop policy if exists %I on public.%I', rec.item_table || '_delete_owner_by_list', rec.item_table);
    execute format(
      'create policy %I on public.%I for delete to authenticated
       using (
         list_id is not null
         and exists (
           select 1 from public.%I l
           where l.id = %I.list_id
             and l.user_id = auth.uid()
         )
       )',
      rec.item_table || '_delete_owner_by_list',
      rec.item_table,
      rec.list_table,
      rec.item_table
    );
  end loop;
end $$;

do $$
begin
  if to_regclass('public.list_tier_meta') is not null then
    execute 'drop policy if exists list_tier_meta_insert_collaborator on public.list_tier_meta';
    execute '
      create policy list_tier_meta_insert_collaborator
      on public.list_tier_meta for insert to authenticated
      with check (
        exists (
          select 1 from public.list_collaborators lc
          where lc.media_type = list_tier_meta.media_type
            and lc.list_id = list_tier_meta.list_id
            and lc.collaborator_id = auth.uid()
            and lc.can_edit = true
            and lc.list_owner_id = list_tier_meta.user_id
        )
      )';

    execute 'drop policy if exists list_tier_meta_update_collaborator on public.list_tier_meta';
    execute '
      create policy list_tier_meta_update_collaborator
      on public.list_tier_meta for update to authenticated
      using (
        exists (
          select 1 from public.list_collaborators lc
          where lc.media_type = list_tier_meta.media_type
            and lc.list_id = list_tier_meta.list_id
            and lc.collaborator_id = auth.uid()
            and lc.can_edit = true
            and lc.list_owner_id = list_tier_meta.user_id
        )
      )
      with check (
        exists (
          select 1 from public.list_collaborators lc
          where lc.media_type = list_tier_meta.media_type
            and lc.list_id = list_tier_meta.list_id
            and lc.collaborator_id = auth.uid()
            and lc.can_edit = true
            and lc.list_owner_id = list_tier_meta.user_id
        )
      )';

    execute 'drop policy if exists list_tier_meta_delete_collaborator on public.list_tier_meta';
    execute '
      create policy list_tier_meta_delete_collaborator
      on public.list_tier_meta for delete to authenticated
      using (
        exists (
          select 1 from public.list_collaborators lc
          where lc.media_type = list_tier_meta.media_type
            and lc.list_id = list_tier_meta.list_id
            and lc.collaborator_id = auth.uid()
            and lc.can_edit = true
            and lc.list_owner_id = list_tier_meta.user_id
        )
      )';
  end if;

  if to_regclass('public.list_tier_ranks') is not null then
    execute 'drop policy if exists list_tier_ranks_insert_collaborator on public.list_tier_ranks';
    execute '
      create policy list_tier_ranks_insert_collaborator
      on public.list_tier_ranks for insert to authenticated
      with check (
        exists (
          select 1 from public.list_collaborators lc
          where lc.media_type = list_tier_ranks.media_type
            and lc.list_id = list_tier_ranks.list_id
            and lc.collaborator_id = auth.uid()
            and lc.can_edit = true
            and lc.list_owner_id = list_tier_ranks.user_id
        )
      )';

    execute 'drop policy if exists list_tier_ranks_update_collaborator on public.list_tier_ranks';
    execute '
      create policy list_tier_ranks_update_collaborator
      on public.list_tier_ranks for update to authenticated
      using (
        exists (
          select 1 from public.list_collaborators lc
          where lc.media_type = list_tier_ranks.media_type
            and lc.list_id = list_tier_ranks.list_id
            and lc.collaborator_id = auth.uid()
            and lc.can_edit = true
            and lc.list_owner_id = list_tier_ranks.user_id
        )
      )
      with check (
        exists (
          select 1 from public.list_collaborators lc
          where lc.media_type = list_tier_ranks.media_type
            and lc.list_id = list_tier_ranks.list_id
            and lc.collaborator_id = auth.uid()
            and lc.can_edit = true
            and lc.list_owner_id = list_tier_ranks.user_id
        )
      )';

    execute 'drop policy if exists list_tier_ranks_delete_collaborator on public.list_tier_ranks';
    execute '
      create policy list_tier_ranks_delete_collaborator
      on public.list_tier_ranks for delete to authenticated
      using (
        exists (
          select 1 from public.list_collaborators lc
          where lc.media_type = list_tier_ranks.media_type
            and lc.list_id = list_tier_ranks.list_id
            and lc.collaborator_id = auth.uid()
            and lc.can_edit = true
            and lc.list_owner_id = list_tier_ranks.user_id
        )
      )';
  end if;
end $$;

commit;
