BEGIN;
BEGIN;
-- Seed brand tables with all brands from Supabase storage bucket
-- Safe to re-run (uses ON CONFLICT DO NOTHING)
-- Run this AFTER rebuild_all.sql

BEGIN;

-- ============================================================
-- CAR BRANDS (64 total)
-- ============================================================
INSERT INTO public.car_brands (name, slug, domain, logo_url, description, category, country, founded, tags) VALUES
  ('Abarth', 'abarth', 'abarth.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/abarth-com.png', 'Italian performance car brand.', 'Performance', 'Italy', '1949', array['performance','italian']),
  ('Acura', 'acura', 'acura.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/acura-com.svg', 'Luxury vehicle division of Honda.', 'Luxury', 'USA', '1986', array['luxury','japanese']),
  ('Audi', 'audi', 'audi.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/audi-com.svg', 'German luxury automobile manufacturer.', 'Luxury', 'Germany', '1909', array['luxury','german']),
  ('BMW', 'bmw', 'bmw.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/bmw-com.svg', 'German luxury vehicle manufacturer.', 'Luxury', 'Germany', '1916', array['luxury','german']),
  ('Bugatti', 'bugatti', 'bugatti.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/bugatti-com.svg', 'French high-performance luxury car brand.', 'Hypercar', 'France', '1909', array['hypercar','luxury']),
  ('Buick', 'buick', 'buick.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/buick-com.png', 'American premium automobile brand.', 'Premium', 'USA', '1899', array['american','premium']),
  ('BYD', 'byd', 'byd.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/byd-com.svg', 'Chinese electric vehicle manufacturer.', 'Electric', 'China', '1995', array['electric','chinese']),
  ('Cadillac', 'cadillac', 'cadillac.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/cadillac-com.svg', 'American luxury vehicle brand.', 'Luxury', 'USA', '1902', array['luxury','american']),
  ('Changan', 'changan', 'changan.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/changan-com.png', 'Chinese automobile manufacturer.', 'Mass Market', 'China', '1862', array['chinese','mass-market']),
  ('Chevrolet', 'chevrolet', 'chevrolet.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/chevrolet-com.svg', 'American automobile brand.', 'Mass Market', 'USA', '1911', array['american','mass-market']),
  ('Chrysler', 'chrysler', 'chrysler.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/chrysler-com.svg', 'American automobile brand.', 'Mass Market', 'USA', '1925', array['american','mass-market']),
  ('Citroën', 'citroen', 'citroen.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/citroen-com.png', 'French automobile brand.', 'Mass Market', 'France', '1919', array['french','mass-market']),
  ('Dacia', 'dacia', 'dacia.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/dacia-com.jpg', 'Budget automobile brand.', 'Budget', 'Romania', '1966', array['budget','european']),
  ('Daihatsu', 'daihatsu', 'daihatsu.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/daihatsu-com.svg', 'Japanese compact car manufacturer.', 'Kei Car', 'Japan', '1907', array['japanese','compact']),
  ('Dodge', 'dodge', 'dodge.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/dodge-com.svg', 'American performance car brand.', 'Performance', 'USA', '1900', array['american','performance']),
  ('Ferrari', 'ferrari', 'ferrari.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/ferrari-com.svg', 'Italian luxury sports car manufacturer.', 'Sports Car', 'Italy', '1939', array['italian','supercar']),
  ('Fiat', 'fiat', 'fiat.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/fiat-com.svg', 'Italian automobile manufacturer.', 'Mass Market', 'Italy', '1899', array['italian','mass-market']),
  ('Ford', 'ford', 'ford.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/ford-com.svg', 'American multinational automobile manufacturer.', 'Mass Market', 'USA', '1903', array['american','mass-market']),
  ('GAC', 'gac', 'gac.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/gac-com.png', 'Chinese automobile manufacturer.', 'Mass Market', 'China', '1997', array['chinese','mass-market']),
  ('Geely', 'geely', 'geely.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/geely-com.svg', 'Chinese multinational automotive company.', 'Mass Market', 'China', '1986', array['chinese','mass-market']),
  ('Genesis', 'genesis', 'genesis.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/genesis-com.png', 'South Korean luxury vehicle brand.', 'Luxury', 'South Korea', '2015', array['luxury','korean']),
  ('GMC', 'gmc', 'gmc.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/gmc-com.png', 'American truck and SUV brand.', 'Truck', 'USA', '1912', array['american','truck']),
  ('Honda', 'honda', 'honda.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/honda-com.svg', 'Japanese automobile manufacturer.', 'Mass Market', 'Japan', '1948', array['japanese','mass-market']),
  ('Hyundai', 'hyundai', 'hyundai.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/hyundai-com.svg', 'South Korean automobile manufacturer.', 'Mass Market', 'South Korea', '1967', array['korean','mass-market']),
  ('Isuzu', 'isuzu', 'isuzu.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/isuzu-com.jpg', 'Japanese commercial vehicle manufacturer.', 'Commercial', 'Japan', '1916', array['japanese','commercial']),
  ('Jaguar', 'jaguar', 'jaguar.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/jaguar-com.svg', 'British luxury vehicle brand.', 'Luxury', 'UK', '1922', array['luxury','british']),
  ('Jeep', 'jeep', 'jeep.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/jeep-com.svg', 'American SUV and off-road brand.', 'SUV', 'USA', '1941', array['american','off-road']),
  ('Kia', 'kia', 'kia.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/kia-com.svg', 'South Korean automobile manufacturer.', 'Mass Market', 'South Korea', '1944', array['korean','mass-market']),
  ('Lamborghini', 'lamborghini', 'lamborghini.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/lamborghini-com.svg', 'Italian luxury sports car manufacturer.', 'Supercar', 'Italy', '1963', array['italian','supercar']),
  ('Lancia', 'lancia', 'lancia.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/lancia-com.jpg', 'Italian automobile manufacturer.', 'Mass Market', 'Italy', '1906', array['italian','mass-market']),
  ('Lexus', 'lexus', 'lexus.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/lexus-com.svg', 'Toyota luxury vehicle brand.', 'Luxury', 'Japan', '1989', array['luxury','japanese']),
  ('Lincoln', 'lincoln', 'lincoln.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/lincoln-com.png', 'American luxury vehicle brand.', 'Luxury', 'USA', '1917', array['luxury','american']),
  ('Lucid Motors', 'lucidmotors', 'lucidmotors.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/lucidmotors-com.svg', 'American electric vehicle manufacturer.', 'Electric', 'USA', '2007', array['electric','luxury']),
  ('Mahindra', 'mahindra', 'mahindra.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/mahindra-com.png', 'Indian automobile manufacturer.', 'SUV', 'India', '1945', array['indian','suv']),
  ('Maserati', 'maserati', 'maserati.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/maserati-com.svg', 'Italian luxury car manufacturer.', 'Luxury', 'Italy', '1914', array['italian','luxury']),
  ('Mazda', 'mazda', 'mazda.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/mazda-com.svg', 'Japanese automobile manufacturer.', 'Mass Market', 'Japan', '1920', array['japanese','mass-market']),
  ('McLaren', 'mclaren', 'mclaren.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/mclaren-com.png', 'British luxury automotive manufacturer.', 'Supercar', 'UK', '1963', array['british','supercar']),
  ('Mercedes-Benz', 'mercedes-benz', 'mercedes-benz.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/mercedes-benz-com.svg', 'German luxury automobile manufacturer.', 'Luxury', 'Germany', '1926', array['luxury','german']),
  ('Mini', 'mini', 'mini.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/mini-com.jpg', 'British automotive brand owned by BMW.', 'Compact', 'UK', '1959', array['british','compact']),
  ('NIO', 'nio', 'nio.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/nio-com.svg', 'Chinese electric vehicle manufacturer.', 'Electric', 'China', '2014', array['electric','chinese']),
  ('Opel', 'opel', 'opel.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/opel-com.svg', 'German automobile manufacturer.', 'Mass Market', 'Germany', '1862', array['german','mass-market']),
  ('Peugeot', 'peugeot', 'peugeot.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/peugeot-com.png', 'French automobile brand.', 'Mass Market', 'France', '1810', array['french','mass-market']),
  ('Polestar', 'polestar', 'polestar.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/polestar-com.svg', 'Swedish electric performance car brand.', 'Electric', 'Sweden', '2017', array['electric','performance']),
  ('Porsche', 'porsche', 'porsche.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/porsche-com.svg', 'German luxury sports car manufacturer.', 'Sports Car', 'Germany', '1931', array['german','sports-car']),
  ('Proton', 'proton', 'proton.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/proton-com.jpg', 'Malaysian automobile manufacturer.', 'Mass Market', 'Malaysia', '1983', array['malaysian','mass-market']),
  ('Ram Trucks', 'ramtrucks', 'ramtrucks.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/ramtrucks-com.svg', 'American truck brand.', 'Truck', 'USA', '1981', array['american','truck']),
  ('Renault', 'renault', 'renault.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/renault-com.svg', 'French automobile manufacturer.', 'Mass Market', 'France', '1899', array['french','mass-market']),
  ('Rimac Automobili', 'rimac-automobili', 'rimac-automobili.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/rimac-automobili-com.png', 'Croatian electric hypercar manufacturer.', 'Hypercar', 'Croatia', '2009', array['electric','hypercar']),
  ('Rivian', 'rivian', 'rivian.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/rivian-com.svg', 'American electric vehicle manufacturer.', 'Electric', 'USA', '2009', array['electric','adventure']),
  ('Rolls-Royce Motor Cars', 'rolls-roycemotorcars', 'rolls-roycemotorcars.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/rolls-roycemotorcars-com.svg', 'British ultra-luxury automobile brand.', 'Ultra Luxury', 'UK', '1904', array['ultra-luxury','british']),
  ('SAAB', 'saab', 'saab.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/saab-com.svg', 'Swedish automobile manufacturer.', 'Mass Market', 'Sweden', '1937', array['swedish','mass-market']),
  ('SAIC Motor', 'saicmotor', 'saicmotor.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/saicmotor-com.svg', 'Chinese automotive manufacturer.', 'Mass Market', 'China', '1945', array['chinese','mass-market']),
  ('Scania', 'scania', 'scania.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/scania-com.svg', 'Swedish commercial vehicle manufacturer.', 'Commercial', 'Sweden', '1891', array['swedish','commercial']),
  ('SEAT', 'seat', 'seat.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/seat-com.png', 'Spanish automobile manufacturer.', 'Mass Market', 'Spain', '1950', array['spanish','mass-market']),
  ('Škoda Auto', 'skoda-auto', 'skoda-auto.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/skoda-auto-com.svg', 'Czech automobile manufacturer.', 'Mass Market', 'Czech Republic', '1895', array['czech','mass-market']),
  ('smart', 'smart', 'smart.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/smart-com.svg', 'Microcar and electric vehicle brand.', 'Compact', 'Germany', '1994', array['compact','electric']),
  ('Subaru', 'subaru', 'subaru.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/subaru-com.svg', 'Japanese automobile manufacturer.', 'Mass Market', 'Japan', '1953', array['japanese','awd']),
  ('Tata Motors', 'tatamotors', 'tatamotors.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/tatamotors-com.svg', 'Indian multinational automotive company.', 'Mass Market', 'India', '1945', array['indian','mass-market']),
  ('Tesla', 'tesla', 'tesla.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/tesla-com.svg', 'American electric vehicle manufacturer.', 'Electric', 'USA', '2003', array['electric','technology']),
  ('Toyota', 'toyota', 'toyota.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/toyota-com.svg', 'Japanese multinational automotive manufacturer.', 'Mass Market', 'Japan', '1937', array['japanese','mass-market']),
  ('Vauxhall', 'vauxhall', 'vauxhall.co.uk', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/vauxhall-co-uk.jpg', 'British automobile manufacturer.', 'Mass Market', 'UK', '1857', array['british','mass-market']),
  ('VinFast', 'vinfast', 'vinfastauto.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/vinfastauto-com.svg', 'Vietnamese electric vehicle manufacturer.', 'Electric', 'Vietnam', '2017', array['electric','vietnamese']),
  ('Volkswagen', 'volkswagen', 'volkswagen.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/volkswagen-com.svg', 'German automobile manufacturer.', 'Mass Market', 'Germany', '1937', array['german','mass-market']),
  ('Volvo Cars', 'volvocars', 'volvocars.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/volvocars-com.png', 'Swedish luxury vehicle manufacturer.', 'Luxury', 'Sweden', '1927', array['swedish','safety']),
  ('Western Star Trucks', 'westernstartrucks', 'westernstartrucks.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/westernstartrucks-com.svg', 'North American truck manufacturer.', 'Commercial', 'USA', '1967', array['american','commercial']),
  ('XPeng', 'xiaopeng', 'xiaopeng.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/xiaopeng-com.png', 'Chinese electric vehicle manufacturer.', 'Electric', 'China', '2014', array['electric','chinese']),
  ('Zeekr', 'zeekrlife', 'zeekrlife.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/car_brands/zeekrlife-com.svg', 'Chinese premium electric vehicle brand.', 'Electric', 'China', '2021', array['electric','chinese'])

-- ============================================================
-- FASHION BRANDS (84 total)
-- ============================================================
INSERT INTO public.fashion_brands (name, slug, domain, logo_url, description, category, country, founded, tags) VALUES
  ('Abercrombie & Fitch', 'abercrombie', 'abercrombie.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/abercrombie-com.svg', 'American casual wear retailer.', 'Casual', 'USA', '1892', array['casual','american']),
  ('American Eagle', 'ae', 'ae.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/ae-com.svg', 'American casual clothing retailer.', 'Casual', 'USA', '1977', array['casual','american']),
  ('Allbirds', 'allbirds', 'allbirds.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/allbirds-com.svg', 'Sustainable footwear brand.', 'Footwear', 'USA', '2016', array['sustainable','footwear']),
  ('ARKET', 'arket', 'arket.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/arket-com.png', 'Scandinavian modern design brand.', 'Modern', 'Sweden', '2017', array['scandinavian','modern']),
  ('ASOS', 'asos', 'asos.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/asos-com.svg', 'British online fashion retailer.', 'Fast Fashion', 'UK', '2000', array['fast fashion','british']),
  ('BAPE', 'bape', 'bape.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/bape-com.jpg', 'Japanese streetwear brand.', 'Streetwear', 'Japan', '1993', array['streetwear','japanese']),
  ('Barbour', 'barbour', 'barbour.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/barbour-com.svg', 'British luxury outerwear brand.', 'Outerwear', 'UK', '1894', array['outerwear','british']),
  ('Birkenstock', 'birkenstock', 'birkenstock.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/birkenstock-com.svg', 'German footwear brand.', 'Footwear', 'Germany', '1774', array['footwear','german']),
  ('Boohoo', 'boohoo', 'boohoo.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/boohoo-com.png', 'British online fashion retailer.', 'Fast Fashion', 'UK', '2006', array['fast fashion','british']),
  ('Burberry', 'burberry', 'burberry.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/burberry-com.svg', 'British luxury fashion house.', 'Luxury', 'UK', '1856', array['luxury','british']),
  ('Canada Goose', 'canadagoose', 'canadagoose.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/canadagoose-com.jpg', 'Canadian outerwear brand.', 'Outerwear', 'Canada', '1957', array['outerwear','canadian']),
  ('Carhartt', 'carhartt', 'carhartt.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/carhartt-com.svg', 'American workwear brand.', 'Workwear', 'USA', '1889', array['workwear','american']),
  ('Celine', 'celine', 'celine.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/celine-com.svg', 'French luxury fashion house.', 'Luxury', 'France', '1945', array['luxury','french']),
  ('Champion', 'champion', 'champion.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/champion-com.png', 'American sportswear brand.', 'Sportswear', 'USA', '1919', array['sportswear','american']),
  ('Chanel', 'chanel', 'chanel.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/chanel-com.svg', 'French luxury fashion house.', 'Luxury', 'France', '1910', array['luxury','french']),
  ('Clarks', 'clarks', 'clarks.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/clarks-com.jpg', 'British footwear brand.', 'Footwear', 'UK', '1825', array['footwear','british']),
  ('Coach', 'coach', 'coach.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/coach-com.svg', 'American luxury fashion brand.', 'Luxury', 'USA', '1941', array['luxury','american']),
  ('Cole Haan', 'colehaan', 'colehaan.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/colehaan-com.svg', 'American footwear and accessories brand.', 'Footwear', 'USA', '1928', array['footwear','american']),
  ('Converse', 'converse', 'converse.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/converse-com.svg', 'American footwear and clothing brand.', 'Footwear', 'USA', '1908', array['footwear','american']),
  ('COS', 'cos', 'cos.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/cos-com.png', 'Modern minimalist fashion brand.', 'Minimalist', 'UK', '2007', array['minimalist','scandinavian']),
  ('Diesel', 'diesel', 'diesel.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/diesel-com.jpg', 'Italian retail clothing company.', 'Denim', 'Italy', '1978', array['denim','italian']),
  ('Dior', 'dior', 'dior.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/dior-com.svg', 'French luxury fashion house.', 'Luxury', 'France', '1946', array['luxury','french']),
  ('Dr. Martens', 'drmartens', 'drmartens.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/drmartens-com.svg', 'British footwear brand.', 'Footwear', 'UK', '1947', array['footwear','british']),
  ('ASICS', 'asics', 'asics.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/asics-com.svg', 'Japanese athletic footwear brand.', 'Sportswear', 'Japan', '1949', array['sportswear','running']),
  ('Everlane', 'everlane', 'everlane.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/everlane-com.png', 'American clothing brand focused on transparency.', 'Basics', 'USA', '2010', array['basics','sustainable']),
  ('Express', 'express', 'express.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/express-com.svg', 'American fashion retailer.', 'Casual', 'USA', '1980', array['casual','american']),
  ('Fendi', 'fendi', 'fendi.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/fendi-com.svg', 'Italian luxury fashion house.', 'Luxury', 'Italy', '1925', array['luxury','italian']),
  ('Fila', 'fila', 'fila.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/fila-com.svg', 'South Korean sportswear brand.', 'Sportswear', 'South Korea', '1911', array['sportswear','korean']),
  ('Forever 21', 'forever21', 'forever21.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/forever21-com.svg', 'American fast fashion retailer.', 'Fast Fashion', 'USA', '1984', array['fast fashion','american']),
  ('Gap', 'gap', 'gap.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/gap-com.svg', 'American clothing retailer.', 'Casual', 'USA', '1969', array['casual','american']),
  ('Givenchy', 'givenchy', 'givenchy.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/givenchy-com.svg', 'French luxury fashion house.', 'Luxury', 'France', '1952', array['luxury','french']),
  ('Golden Goose', 'goldengoose', 'goldengoose.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/goldengoose-com.svg', 'Italian luxury sneaker brand.', 'Luxury', 'Italy', '2000', array['luxury','sneakers']),
  ('Guess', 'guess', 'guess.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/guess-com.svg', 'American clothing brand.', 'Casual', 'USA', '1981', array['casual','american']),
  ('Gucci', 'gucci', 'gucci.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/gucci-com.svg', 'Italian luxury fashion house.', 'Luxury', 'Italy', '1921', array['luxury','italian']),
  ('Gymshark', 'gymshark', 'gymshark.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/gymshark-com.png', 'British fitness apparel brand.', 'Activewear', 'UK', '2012', array['activewear','fitness']),
  ('H&M', 'hm', 'hm.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/hm-com.svg', 'Global fashion retailer.', 'Fast Fashion', 'Sweden', '1947', array['fast fashion']),
  ('Hermès', 'hermes', 'hermes.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/hermes-com.svg', 'French luxury fashion house.', 'Luxury', 'France', '1837', array['luxury','french']),
  ('HUGO BOSS', 'hugoboss', 'hugoboss.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/hugoboss-com.svg', 'German luxury fashion house.', 'Luxury', 'Germany', '1924', array['luxury','german']),
  ('J.Crew', 'jcrew', 'jcrew.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/jcrew-com.svg', 'American casual apparel brand.', 'Casual', 'USA', '1947', array['casual','american']),
  ('Jimmy Choo', 'jimmychoo', 'jimmychoo.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/jimmychoo-com.svg', 'British luxury fashion house.', 'Luxury', 'UK', '1996', array['luxury','shoes']),
  ('Kate Spade', 'katespade', 'katespade.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/katespade-com.svg', 'American luxury fashion brand.', 'Luxury', 'USA', '1993', array['luxury','handbags']),
  ('Kith', 'kith', 'kith.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/kith-com.svg', 'Streetwear brand and retailer.', 'Streetwear', 'USA', '2011', array['streetwear','american']),
  ('Lacoste', 'lacoste', 'lacoste.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/lacoste-com.png', 'French clothing brand.', 'Sportswear', 'France', '1933', array['sportswear','french']),
  ('Lee', 'lee', 'lee.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/lee-com.svg', 'American denim brand.', 'Denim', 'USA', '1889', array['denim','american']),
  ('Levi''s', 'levi', 'levi.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/levi-com.svg', 'American denim and clothing brand.', 'Denim', 'USA', '1853', array['denim','american']),
  ('Loewe', 'loewe', 'loewe.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/loewe-com.svg', 'Spanish luxury fashion house.', 'Luxury', 'Spain', '1846', array['luxury','spanish']),
  ('Longchamp', 'longchamp', 'longchamp.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/longchamp-com.svg', 'French leather goods brand.', 'Accessories', 'France', '1948', array['leather','french']),
  ('Louis Vuitton', 'louisvuitton', 'louisvuitton.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/louisvuitton-com.svg', 'French luxury fashion house.', 'Luxury', 'France', '1854', array['luxury','french']),
  ('Mango', 'mango', 'mango.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/mango-com.jpg', 'Spanish fashion retailer.', 'Fast Fashion', 'Spain', '1984', array['fast fashion','spanish']),
  ('Marc Jacobs', 'marcjacobs', 'marcjacobs.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/marcjacobs-com.svg', 'American fashion designer brand.', 'Luxury', 'USA', '1984', array['luxury','american']),
  ('Massimo Dutti', 'massimodutti', 'massimodutti.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/massimodutti-com.svg', 'Spanish clothing brand.', 'Contemporary', 'Spain', '1985', array['contemporary','spanish']),
  ('Michael Kors', 'michaelkors', 'michaelkors.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/michaelkors-com.svg', 'American luxury fashion brand.', 'Luxury', 'USA', '1981', array['luxury','american']),
  ('Moncler', 'moncler', 'moncler.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/moncler-com.svg', 'French luxury fashion brand.', 'Outerwear', 'France', '1952', array['luxury','outerwear']),
  ('New Balance', 'newbalance', 'newbalance.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/newbalance-com.svg', 'American footwear manufacturer.', 'Footwear', 'USA', '1906', array['footwear','running']),
  ('Nike', 'nike', 'nike.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/nike-com.svg', 'Global sportswear brand.', 'Sportswear', 'USA', '1964', array['sportswear','sneakers']),
  ('Nordstrom', 'nordstrom', 'nordstrom.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/nordstrom-com.svg', 'American luxury department store.', 'Department Store', 'USA', '1901', array['department store','american']),
  ('Oakley', 'oakley', 'oakley.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/oakley-com.svg', 'American sportswear and eyewear brand.', 'Accessories', 'USA', '1975', array['eyewear','sportswear']),
  ('Off-White', 'offwhite', 'offwhite.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/offwhite-com.svg', 'Luxury streetwear label.', 'Streetwear', 'Italy', '2012', array['streetwear','luxury']),
  ('PacSun', 'pacsun', 'pacsun.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/pacsun-com.jpg', 'American lifestyle retail brand.', 'Casual', 'USA', '1980', array['casual','california']),
  ('Patagonia', 'patagonia', 'patagonia.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/patagonia-com.svg', 'American outdoor clothing brand.', 'Outdoor', 'USA', '1973', array['outdoor','sustainable']),
  ('Piaget', 'piaget', 'piaget.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/piaget-com.svg', 'Swiss luxury watch and jewelry brand.', 'Watches', 'Switzerland', '1874', array['watches','jewelry']),
  ('Prada', 'prada', 'prada.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/prada-com.svg', 'Luxury fashion house.', 'Luxury', 'Italy', '1913', array['luxury']),
  ('Puma', 'puma', 'puma.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/puma-com.svg', 'German sportswear brand.', 'Sportswear', 'Germany', '1948', array['sportswear','german']),
  ('rag & bone', 'ragbone', 'rag-bone.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/rag-bone-com.png', 'American fashion brand.', 'Contemporary', 'USA', '2002', array['contemporary','american']),
  ('Ralph Lauren', 'ralphlauren', 'ralphlauren.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/ralphlauren-com.svg', 'American luxury fashion brand.', 'Luxury', 'USA', '1967', array['luxury','american']),
  ('Reebok', 'reebok', 'reebok.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/reebok-com.svg', 'American athletic footwear brand.', 'Sportswear', 'USA', '1958', array['sportswear','american']),
  ('Reiss', 'reiss', 'reiss.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/reiss-com.png', 'British fashion brand.', 'Contemporary', 'UK', '1971', array['contemporary','british']),
  ('Rolex', 'rolex', 'rolex.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/rolex-com.png', 'Swiss luxury watch manufacturer.', 'Watches', 'Switzerland', '1905', array['watches','luxury']),
  ('Sandro', 'sandro', 'sandro-paris.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/sandro-paris-com.jpg', 'French contemporary fashion brand.', 'Contemporary', 'France', '1984', array['contemporary','french']),
  ('Saucony', 'saucony', 'saucony.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/saucony-com.svg', 'American athletic footwear brand.', 'Footwear', 'USA', '1898', array['footwear','running']),
  ('Skechers', 'skechers', 'skechers.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/skechers-com.svg', 'American footwear brand.', 'Footwear', 'USA', '1992', array['footwear','american']),
  ('Stone Island', 'stoneisland', 'stoneisland.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/stoneisland-com.svg', 'Technical outerwear.', 'Streetwear', 'Italy', '1982', array['outerwear']),
  ('Stradivarius', 'stradivarius', 'stradivarius.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/stradivarius-com.svg', 'Spanish fast fashion brand.', 'Fast Fashion', 'Spain', '1994', array['fast fashion','spanish']),
  ('Supreme', 'supreme', 'supremenewyork.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/supremenewyork-com.svg', 'Streetwear brand.', 'Streetwear', 'USA', '1994', array['streetwear']),
  ('Swarovski', 'swarovski', 'swarovski.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/swarovski-com.svg', 'Austrian luxury jewelry brand.', 'Jewelry', 'Austria', '1895', array['jewelry','luxury']),
  ('Ted Baker', 'tedbaker', 'ted-baker.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/ted-baker-com.svg', 'British luxury clothing brand.', 'Luxury', 'UK', '1987', array['luxury','british']),
  ('Thom Browne', 'thombrowne', 'thom-browne.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/thom-browne-com.svg', 'American luxury fashion brand.', 'Luxury', 'USA', '2001', array['luxury','american']),
  ('Timberland', 'timberland', 'timberland.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/timberland-com.png', 'American outdoor brand.', 'Footwear', 'USA', '1952', array['footwear','outdoor']),
  ('Merrell', 'merrell', 'merrell.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/merrell-com.png', 'American hiking footwear brand.', 'Footwear', 'USA', '1981', array['footwear','hiking']),
  ('Tom Ford', 'tomford', 'tom-ford.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/tom-ford-com.svg', 'American luxury fashion brand.', 'Luxury', 'USA', '2005', array['luxury','american']),
  ('Tommy Hilfiger', 'tommy', 'tommy.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/tommy-com.svg', 'American fashion brand.', 'Casual', 'USA', '1985', array['casual','american']),
  ('Topshop', 'topshop', 'topshop.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/topshop-com.jpg', 'British fast fashion retailer.', 'Fast Fashion', 'UK', '1964', array['fast fashion','british']),
  ('Tory Burch', 'toryburch', 'toryburch.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/toryburch-com.svg', 'American fashion brand.', 'Luxury', 'USA', '2004', array['luxury','american']),
  ('Tudor', 'tudorwatch', 'tudorwatch.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/tudorwatch-com.png', 'Swiss luxury watch brand.', 'Watches', 'Switzerland', '1926', array['watches','luxury']),
  ('UGG', 'ugg', 'ugg.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/ugg-com.svg', 'American footwear brand.', 'Footwear', 'USA', '1978', array['footwear','american']),
  ('Umbro', 'umbro', 'umbro.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/umbro-com.svg', 'British sportswear brand.', 'Sportswear', 'UK', '1920', array['sportswear','british']),
  ('Under Armour', 'underarmour', 'underarmour.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/underarmour-com.svg', 'American sportswear brand.', 'Sportswear', 'USA', '1996', array['sportswear','american']),
  ('Uniqlo', 'uniqlo', 'uniqlo.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/uniqlo-com.svg', 'Japanese casualwear brand.', 'Basics', 'Japan', '1949', array['basics','japanese']),
  ('Urban Outfitters', 'urbanoutfitters', 'urbanoutfitters.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/urbanoutfitters-com.svg', 'American lifestyle retailer.', 'Casual', 'USA', '1970', array['casual','american']),
  ('Vacheron Constantin', 'vacheron-constantin', 'vacheron-constantin.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/vacheron-constantin-com.png', 'Swiss luxury watch manufacturer.', 'Watches', 'Switzerland', '1755', array['watches','ultra-luxury']),
  ('Valentino', 'valentino', 'valentino.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/valentino-com.jpg', 'Italian luxury fashion house.', 'Luxury', 'Italy', '1960', array['luxury','italian']),
  ('Vans', 'vans', 'vans.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/vans-com.svg', 'American skateboarding footwear brand.', 'Footwear', 'USA', '1966', array['footwear','skate']),
  ('Versace', 'versace', 'versace.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/versace-com.svg', 'Italian luxury fashion house.', 'Luxury', 'Italy', '1978', array['luxury','italian']),
  ('Victoria''s Secret', 'victoriassecret', 'victoriassecret.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/victoriassecret-com.svg', 'American lingerie retailer.', 'Lingerie', 'USA', '1977', array['lingerie','american']),
  ('Vuori', 'vuoriclothing', 'vuoriclothing.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/vuoriclothing-com.png', 'American activewear brand.', 'Activewear', 'USA', '2013', array['activewear','california']),
  ('Weekday', 'weekday', 'weekday.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/weekday-com.svg', 'Swedish fashion retailer.', 'Casual', 'Sweden', '2002', array['casual','scandinavian']),
  ('Wrangler', 'wrangler', 'wrangler.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/wrangler-com.svg', 'American denim brand.', 'Denim', 'USA', '1947', array['denim','american']),
  ('YSL', 'ysl', 'ysl.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/ysl-com.svg', 'French luxury fashion house.', 'Luxury', 'France', '1961', array['luxury','french']),
  ('Zalando', 'zalando', 'zalando.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/zalando-com.svg', 'European online fashion platform.', 'E-Commerce', 'Germany', '2008', array['e-commerce','german']),
  ('Zara', 'zara', 'zara.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/zara-com.jpeg', 'Spanish fast fashion retailer.', 'Fast Fashion', 'Spain', '1975', array['fast fashion','spanish']),
  ('Zegna', 'zegna', 'zegna.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/zegna-com.svg', 'Italian luxury fashion house.', 'Luxury', 'Italy', '1910', array['luxury','italian']),
  ('Zenith', 'zenith-watches', 'zenith-watches.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/zenith-watches-com.jpg', 'Swiss luxury watch manufacturer.', 'Watches', 'Switzerland', '1865', array['watches','luxury']),
  ('Adidas', 'adidas', 'adidas.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/adidas-com.svg', 'Athletic apparel and footwear.', 'Sportswear', 'Germany', '1949', array['sportswear','sneakers']),
  ('Balenciaga', 'balenciaga', 'balenciaga.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/fashion_brands/balenciaga-com.svg', 'Luxury fashion house.', 'Luxury', 'France', '1917', array['luxury'])

-- ============================================================
-- FOOD BRANDS (59 total)
-- ============================================================
INSERT INTO public.food_brands (name, slug, domain, logo_url, description, category, country, founded, tags) VALUES
  ('Applebee''s', 'applebees', 'applebees.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/applebees-com.png', 'American casual dining chain.', 'Casual Dining', 'USA', '1980', array['casual dining','american']),
  ('Arby''s', 'arbys', 'arbys.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/arbys-com.svg', 'American fast-food sandwich chain.', 'Fast Food', 'USA', '1964', array['sandwiches','fast food']),
  ('Bojangles''', 'bojangles', 'bojangles.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/bojangles-com.svg', 'American fast food chain.', 'Fast Food', 'USA', '1977', array['chicken','fast food']),
  ('Buffalo Wild Wings', 'buffalowildwings', 'buffalowildwings.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/buffalowildwings-com.svg', 'American casual dining restaurant chain.', 'Casual Dining', 'USA', '1982', array['wings','sports-bar']),
  ('Burger King', 'burgerking', 'burgerking.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/burgerking-com.svg', 'Home of the Whopper.', 'Fast Food', 'USA', '1954', array['burgers','fast food']),
  ('Carrabba''s Italian Grill', 'carrabbas', 'carrabbas.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/carrabbas-com.svg', 'Italian-American restaurant chain.', 'Casual Dining', 'USA', '1986', array['italian','casual dining']),
  ('Chick-fil-A', 'chick-fil-a', 'chick-fil-a.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/chick-fil-a-com.svg', 'American chicken sandwich chain.', 'Fast Food', 'USA', '1946', array['chicken','fast food']),
  ('Chipotle', 'chipotle', 'chipotle.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/chipotle-com.svg', 'Fast casual Mexican grill.', 'Fast Casual', 'USA', '1993', array['mexican','fast casual']),
  ('Chili''s', 'chilis', 'chilis.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/chilis-com.svg', 'American casual dining restaurant chain.', 'Casual Dining', 'USA', '1975', array['casual dining','tex-mex']),
  ('Cracker Barrel', 'crackerbarrel', 'crackerbarrel.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/crackerbarrel-com.svg', 'American restaurant and gift shop chain.', 'Casual Dining', 'USA', '1969', array['southern','casual dining']),
  ('Culver''s', 'culvers', 'culvers.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/culvers-com.svg', 'American fast food chain.', 'Fast Food', 'USA', '1984', array['burgers','fast food']),
  ('Dairy Queen', 'dairyqueen', 'dairyqueen.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/dairyqueen-com.svg', 'American soft-serve ice cream chain.', 'Fast Food', 'USA', '1940', array['ice cream','fast food']),
  ('Denny''s', 'dennys', 'dennys.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/dennys-com.svg', 'American diner chain.', 'Diner', 'USA', '1953', array['diner','breakfast']),
  ('Domino''s', 'dominos', 'dominos.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/dominos-com.svg', 'Pizza delivery chain.', 'Pizza', 'USA', '1960', array['pizza']),
  ('Dunkin''', 'dunkin', 'dunkin.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/dunkin-com.png', 'American coffee and donut chain.', 'Coffee', 'USA', '1950', array['coffee','donuts']),
  ('In-N-Out Burger', 'innout', 'in-n-out.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/in-n-out-com.svg', 'American fast food chain.', 'Fast Food', 'USA', '1948', array['burgers','fast food']),
  ('Jack in the Box', 'jackinthebox', 'jackinthebox.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/jackinthebox-com.svg', 'American fast food chain.', 'Fast Food', 'USA', '1951', array['fast food','burgers']),
  ('Jamba', 'jamba', 'jamba.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/jamba-com.jpg', 'American smoothie and juice chain.', 'Smoothies', 'USA', '1990', array['smoothies','health']),
  ('KFC', 'kfc', 'kfc.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/kfc-com.svg', 'Fried chicken specialists.', 'Fast Food', 'USA', '1952', array['chicken','fast food']),
  ('Little Caesars', 'littlecaesars', 'littlecaesars.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/littlecaesars-com.svg', 'American pizza chain.', 'Pizza', 'USA', '1959', array['pizza','fast food']),
  ('McDonald''s', 'mcdonalds', 'mcdonalds.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/mcdonalds-com.svg', 'American fast-food chain.', 'Fast Food', 'USA', '1940', array['burgers','fast food']),
  ('Nando''s', 'nandos', 'nandos.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/nandos-com.svg', 'South African restaurant chain.', 'Casual Dining', 'South Africa', '1987', array['chicken','peri-peri']),
  ('Noodles & Company', 'noodles', 'noodles.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/noodles-com.png', 'American fast-casual restaurant chain.', 'Fast Casual', 'USA', '1977', array['pasta','fast casual']),
  ('Olive Garden', 'olivegarden', 'olive-garden.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/olive-garden-com.svg', 'American casual dining restaurant chain.', 'Casual Dining', 'USA', '1982', array['italian','casual dining']),
  ('Outback Steakhouse', 'outback', 'outback.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/outback-com.png', 'American casual dining steakhouse chain.', 'Casual Dining', 'USA', '1988', array['steakhouse','casual dining']),
  ('Panda Express', 'pandaexpress', 'pandaexpress.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/pandaexpress-com.jpg', 'American Chinese fast food chain.', 'Fast Food', 'USA', '1983', array['chinese','fast food']),
  ('Panera Bread', 'panerabread', 'panerabread.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/panerabread-com.svg', 'American bakery-café chain.', 'Fast Casual', 'USA', '1987', array['bakery','fast casual']),
  ('Papa John''s', 'papajohns', 'papajohns.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/papajohns-com.svg', 'American pizza delivery chain.', 'Pizza', 'USA', '1984', array['pizza','fast food']),
  ('Peet''s Coffee', 'peets', 'peets.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/peets-com.svg', 'American coffee roaster and retailer.', 'Coffee', 'USA', '1966', array['coffee','specialty']),
  ('Pizza Hut', 'pizzahut', 'pizzahut.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/pizzahut-com.svg', 'Pizza restaurant chain.', 'Pizza', 'USA', '1958', array['pizza']),
  ('Popeyes', 'popeyes', 'popeyes.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/popeyes-com.svg', 'American fast food chain.', 'Fast Food', 'USA', '1972', array['chicken','fast food']),
  ('Potbelly', 'potbelly', 'potbelly.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/potbelly-com.jpg', 'American sandwich shop chain.', 'Fast Casual', 'USA', '1977', array['sandwiches','fast casual']),
  ('Qdoba', 'qdoba', 'qdoba.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/qdoba-com.svg', 'American fast-casual restaurant chain.', 'Fast Casual', 'USA', '1995', array['mexican','fast casual']),
  ('Raising Cane''s', 'raisingcanes', 'raisingcanes.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/raisingcanes-com.png', 'American fast food chicken chain.', 'Fast Food', 'USA', '1996', array['chicken','fast food']),
  ('Red Robin', 'redrobin', 'redrobin.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/redrobin-com.svg', 'American casual dining burger chain.', 'Casual Dining', 'USA', '1969', array['burgers','casual dining']),
  ('Sbarro', 'sbarro', 'sbarro.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/sbarro-com.svg', 'American pizza restaurant chain.', 'Pizza', 'USA', '1956', array['pizza','fast food']),
  ('Shake Shack', 'shakeshack', 'shakeshack.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/shakeshack-com.svg', 'Modern burger stand.', 'Fast Casual', 'USA', '2004', array['burgers','fast casual']),
  ('Smoothie King', 'smoothieking', 'smoothieking.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/smoothieking-com.svg', 'American smoothie chain.', 'Smoothies', 'USA', '1973', array['smoothies','health']),
  ('Sonic Drive-In', 'sonicdrivein', 'sonicdrivein.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/sonicdrivein-com.png', 'American drive-in fast food chain.', 'Fast Food', 'USA', '1953', array['drive-in','fast food']),
  ('Starbucks', 'starbucks', 'starbucks.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/starbucks-com.png', 'American coffeehouse chain.', 'Coffee', 'USA', '1971', array['coffee','beverages']),
  ('Subway', 'subway', 'subway.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/subway-com.svg', 'American sandwich chain.', 'Fast Food', 'USA', '1965', array['sandwiches','fast food']),
  ('Sweetgreen', 'sweetgreen', 'sweetgreen.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/sweetgreen-com.svg', 'American fast casual salad chain.', 'Fast Casual', 'USA', '2007', array['salads','fast casual']),
  ('Taco Bell', 'tacobell', 'tacobell.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/tacobell-com.jpg', 'Mexican-inspired fast food chain.', 'Fast Food', 'USA', '1962', array['tacos','fast food']),
  ('Texas Roadhouse', 'texasroadhouse', 'texasroadhouse.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/texasroadhouse-com.svg', 'American steakhouse chain.', 'Casual Dining', 'USA', '1993', array['steakhouse','casual dining']),
  ('The Capital Grille', 'thecapitalgrille', 'thecapitalgrille.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/thecapitalgrille-com.svg', 'American fine dining steakhouse chain.', 'Fine Dining', 'USA', '1990', array['steakhouse','fine dining']),
  ('The Cheesecake Factory', 'thecheesecakefactory', 'thecheesecakefactory.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/thecheesecakefactory-com.png', 'American restaurant chain.', 'Casual Dining', 'USA', '1978', array['casual dining','cheesecake']),
  ('Tim Hortons', 'timhortons', 'timhortons.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/timhortons-com.svg', 'Canadian coffee and fast food chain.', 'Coffee', 'Canada', '1964', array['coffee','canadian']),
  ('TLJUS', 'tljus', 'tljus.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/tljus-com.jpg', 'Restaurant brand.', 'Casual Dining', 'USA', '', array['restaurant','casual dining']),
  ('Torchy''s Tacos', 'torchystacos', 'torchystacos.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/torchystacos-com.png', 'Tex-Mex taco chain.', 'Fast Casual', 'USA', '2006', array['tacos','fast casual']),
  ('TX Chicken', 'txchicken', 'txchicken.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/txchicken-com.png', 'Chicken restaurant chain.', 'Fast Food', 'USA', '', array['chicken','fast food']),
  ('Wagamama', 'wagamama', 'wagamama.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/wagamama-com.svg', 'British restaurant chain specializing in Asian food.', 'Casual Dining', 'UK', '1992', array['asian','casual dining']),
  ('Wendy''s', 'wendys', 'wendys.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/wendys-com.svg', 'American fast food hamburger chain.', 'Fast Food', 'USA', '1969', array['burgers','fast food']),
  ('Whataburger', 'whataburger', 'whataburger.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/whataburger-com.svg', 'American fast food chain.', 'Fast Food', 'USA', '1950', array['burgers','fast food']),
  ('White Castle', 'whitecastle', 'whitecastle.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/whitecastle-com.jpg', 'American slider hamburger chain.', 'Fast Food', 'USA', '1921', array['burgers','fast food']),
  ('Wingstop', 'wingstop', 'wingstop.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/wingstop-com.svg', 'American chicken wing chain.', 'Fast Food', 'USA', '1994', array['wings','fast food']),
  ('YO! Sushi', 'yosushi', 'yosushi.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/yosushi-com.svg', 'British sushi restaurant chain.', 'Casual Dining', 'UK', '1997', array['sushi','casual dining']),
  ('Zaxby''s', 'zaxbys', 'zaxbys.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/zaxbys-com.png', 'American fast food chicken chain.', 'Fast Food', 'USA', '1990', array['chicken','fast food']),
  ('Zippy''s', 'zippys', 'zippys.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/zippys-com.svg', 'Hawaiian restaurant chain.', 'Casual Dining', 'USA', '1966', array['hawaiian','casual dining']),
  ('Zoe''s Kitchen', 'zoeskitchen', 'zoeskitchen.com', 'https://gfkhjbztayjyojsgdpgk.supabase.co/storage/v1/object/public/brand-logos/food_brands/zoeskitchen-com.jpg', 'American Mediterranean fast casual chain.', 'Fast Casual', 'USA', '1995', array['mediterranean','fast casual']),




COMMIT;

COMMIT;
