begin;

create table if not exists public.list_tier_meta (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_type text not null check (media_type in ('movie', 'tv', 'game', 'book', 'music', 'restaurant')),
  list_id text not null,
  list_kind text not null default 'standard' check (list_kind in ('standard', 'tier')),
  max_rank integer null check (max_rank is null or max_rank > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, media_type, list_id)
);

create table if not exists public.list_tier_ranks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_type text not null check (media_type in ('movie', 'tv', 'game', 'book', 'music', 'restaurant')),
  list_id text not null,
  item_id text not null,
  rank integer not null check (rank > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, media_type, list_id, item_id)
);

create index if not exists idx_list_tier_meta_lookup
  on public.list_tier_meta (media_type, list_id);

create index if not exists idx_list_tier_ranks_lookup
  on public.list_tier_ranks (media_type, list_id, rank, item_id);

alter table public.list_tier_meta enable row level security;
alter table public.list_tier_ranks enable row level security;

drop policy if exists list_tier_meta_select_auth on public.list_tier_meta;
create policy list_tier_meta_select_auth
  on public.list_tier_meta
  for select
  to authenticated
  using (true);

drop policy if exists list_tier_meta_insert_owner on public.list_tier_meta;
create policy list_tier_meta_insert_owner
  on public.list_tier_meta
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists list_tier_meta_update_owner on public.list_tier_meta;
create policy list_tier_meta_update_owner
  on public.list_tier_meta
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists list_tier_meta_delete_owner on public.list_tier_meta;
create policy list_tier_meta_delete_owner
  on public.list_tier_meta
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists list_tier_ranks_select_auth on public.list_tier_ranks;
create policy list_tier_ranks_select_auth
  on public.list_tier_ranks
  for select
  to authenticated
  using (true);

drop policy if exists list_tier_ranks_insert_owner on public.list_tier_ranks;
create policy list_tier_ranks_insert_owner
  on public.list_tier_ranks
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists list_tier_ranks_update_owner on public.list_tier_ranks;
create policy list_tier_ranks_update_owner
  on public.list_tier_ranks
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists list_tier_ranks_delete_owner on public.list_tier_ranks;
create policy list_tier_ranks_delete_owner
  on public.list_tier_ranks
  for delete
  to authenticated
  using (auth.uid() = user_id);

commit;
